# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

  name: Node.js CI

  on:
    push:
        branches: ["main"]
    pull_request: 
          branches: ["main", "dev"]

  jobs:
      mongo_init:
          name: Mongo Setup
          runs-on: ubuntu-latest
          defaults:
              run:
                  working-directory: ./quirknotes/backend
          steps:
              - uses: actions/checkout@v3
              - run: mongod --dbpath=./data/db
      server_init:
          name: Server Setup
          runs-on: ubuntu-latest
          defaults:
              run:
                  working-directory: ./quirknotes/backend
          strategy:
              matrix:
                  node-version: [20.x]
          steps:
              - uses: actions/checkout@v3
                with:
                  node-version: ${{ matrix.node-version }}
              - run: npm run dev
      build:
          name: Backend test
          runs-on: ubuntu-latest

          defaults:
              run:
                  working-directory: ./quirknotes/backend

          strategy:
              matrix:
                  node-version: [20.x]

          steps:
              - uses: actions/checkout@v3

              - name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                  node-version: ${{ matrix.node-version }}
              - run: npm i
              - run: npm test
